# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create --resource-group BicepGroup --template-file main.bicep sqlServerAdministratorLogin=$(SQLSERVERADMINISTRATORLOGIN) sqlServerAdministratorLoginPassword=$(SQLSERVERADMINISTRATORLOGINPASSWORD)'
